structures_folder: data/antibody #data/local_pdb #structures #in this folde either pdb files are placed or downloaded from pdb into this folder
preprocessed_structures: data/antibody_test_structures # sructures that are cleaned up fully. 
pdb_stems: 7LQV
mutants: data/example_mutations.csv
mutants_templates: data/example_mations_templates.fasta 
workdir: antibody_run
conformers_to_evaluate: 0 # zero - mean static evaluation